### ISSUE TITLE
[BUG] WOLF ERROR

### ISSUE THREAD

**Issue by pelicano0** [Geik-xyz/Farmer-v6#108]
**Describe the bug**
In version 1.21.1, when right-clicking an untamed wolf with a bone or wolf armor, error messages are spammed in the console.

**To Reproduce**
Run farmer 1.21.1 version.

**Logging**
```
[12:39:48 ERROR]: Could not pass event PlayerInteractEvent to Farmer vv6-b107
java.lang.NoClassDefFoundError: Could not initialize class xyz.geik.farmer.shades.nbtapi.NBTReflectionUtil
        at Farmer-v6-b107.jar/xyz.geik.farmer.shades.nbtapi.NBTCompound.getInteger(NBTCompound.java:226) ~[Farmer-v6-b107.jar:?]
        at Farmer-v6-b107.jar/xyz.geik.farmer.modules.voucher.handlers.VoucherEvent.lambda$onVoucherUseEvent$0(VoucherEvent.java:52) ~[Farmer-v6-b107.jar:?]
        at Farmer-v6-b107.jar/xyz.geik.farmer.shades.nbtapi.NBT.get(NBT.java:102) ~[Farmer-v6-b107.jar:?]
        at Farmer-v6-b107.jar/xyz.geik.farmer.modules.voucher.handlers.VoucherEvent.onVoucherUseEvent(VoucherEvent.java:52) ~[Farmer-v6-b107.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor967.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-2327-4b57bed]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:604) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:538) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:2020) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:44) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:11) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1581) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1558) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1551) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1510) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1517) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1362) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NullPointerException [in thread "Server thread"]
        at java.base/java.util.ImmutableCollections$MapN.probe(ImmutableCollections.java:1328) ~[?:?]
        at java.base/java.util.ImmutableCollections$MapN.get(ImmutableCollections.java:1242) ~[?:?]
        at java.base/java.util.ImmutableCollections$AbstractImmutableMap.getOrDefault(ImmutableCollections.java:1097) ~[?:?]
        at io.papermc.paper.pluginremap.reflect.PaperReflection.mapDeclaredFieldName(PaperReflection.java:79) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.getDeclaredField(AbstractDefaultRulesReflectionProxy.java:90) ~[reflection-rewriter-runtime-0.0.3.jar:?]
        at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.getDeclaredField(Unknown Source) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at Farmer-v6-b107.jar/xyz.geik.farmer.shades.nbtapi.NBTReflectionUtil.<clinit>(NBTReflectionUtil.java:59) ~[Farmer-v6-b107.jar:?]
        at Farmer-v6-b107.jar/xyz.geik.farmer.shades.nbtapi.NBTCompound.getInteger(NBTCompound.java:226) ~[Farmer-v6-b107.jar:?]
        at Farmer-v6-b107.jar/xyz.geik.farmer.modules.voucher.handlers.VoucherEvent.lambda$onVoucherUseEvent$0(VoucherEvent.java:52) ~[Farmer-v6-b107.jar:?]
        at Farmer-v6-b107.jar/xyz.geik.farmer.shades.nbtapi.NBT.get(NBT.java:102) ~[Farmer-v6-b107.jar:?]
        at Farmer-v6-b107.jar/xyz.geik.farmer.modules.voucher.handlers.VoucherEvent.onVoucherUseEvent(VoucherEvent.java:52) ~[Farmer-v6-b107.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor967.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-2327-4b57bed]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:604) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:538) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:2020) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:44) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:11) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1581) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1558) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1551) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1510) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1632) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1342) ~[purpur-1.21.1.jar:1.21.1-2327-4b57bed]
        ... 2 more
```

**Give me which version of Farmer do you use**
v6-b107

**Write your server version**
1.21.1 Purpur

**Comment by pelicano0** [comment]
In version 1.21.1, most things aren't working.

**Comment by poyrazinan** [comment]
Please use b108 in releases.
