### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by berktuaga** [Geik-xyz/Farmer-v6#51]
[BUG] Farmer v6 is not working.

Whenever I install the Farmer v6 plugin, I encounter an error in the console and can't get the plugin to run.

**Logging**
[20:56:27] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'farmer' in xyz.geik.farmer.shades.glib.shades.triumphteam.cmd.bukkit.BukkitCommand(farmer)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:150) ~[Requlogia.jar:git-TacoSpigot-"95870a93"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[Requlogia.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1167) [Requlogia.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:982) [Requlogia.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [Requlogia.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [Requlogia.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [Requlogia.jar:git-TacoSpigot-"95870a93"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_412]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_412]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [Requlogia.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:776) [Requlogia.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [Requlogia.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:715) [Requlogia.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:618) [Requlogia.jar:git-TacoSpigot-"95870a93"]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_412]
Caused by: xyz.geik.farmer.shades.glib.shades.triumphteam.cmd.core.exceptions.CommandExecutionException: An error occurred while executing the command. On "farmer" command on "TH_DEFAULT" sub command.
	at xyz.geik.farmer.shades.glib.shades.triumphteam.cmd.core.AbstractSubCommand.lambda$execute$0(AbstractSubCommand.java:184) ~[?:?]
	at xyz.geik.farmer.shades.glib.shades.triumphteam.cmd.core.execution.SyncExecutionProvider.execute(SyncExecutionProvider.java:32) ~[?:?]
	at xyz.geik.farmer.shades.glib.shades.triumphteam.cmd.core.AbstractSubCommand.execute(AbstractSubCommand.java:180) ~[?:?]
	at xyz.geik.farmer.shades.glib.shades.triumphteam.cmd.bukkit.BukkitCommand.execute(BukkitCommand.java:104) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143) ~[Requlogia.jar:git-TacoSpigot-"95870a93"]
	... 14 more
Caused by: java.lang.NoSuchMethodError: me.ryanhamshire.GriefPrevention.Claim.getOwnerID()Ljava/util/UUID;
	at xyz.geik.farmer.integrations.grief.GriefPrevent.getOwnerUUID(GriefPrevent.java:38) ~[?:?]
	at xyz.geik.farmer.commands.FarmerCommand.defaultCommand(FarmerCommand.java:63) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_412]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_412]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_412]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_412]
	at xyz.geik.farmer.shades.glib.shades.triumphteam.cmd.core.AbstractSubCommand.lambda$execute$0(AbstractSubCommand.java:182) ~[?:?]
	at xyz.geik.farmer.shades.glib.shades.triumphteam.cmd.core.execution.SyncExecutionProvider.execute(SyncExecutionProvider.java:32) ~[?:?]
	at xyz.geik.farmer.shades.glib.shades.triumphteam.cmd.core.AbstractSubCommand.execute(AbstractSubCommand.java:180) ~[?:?]
	at xyz.geik.farmer.shades.glib.shades.triumphteam.cmd.bukkit.BukkitCommand.execute(BukkitCommand.java:104) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143) ~[Requlogia.jar:git-TacoSpigot-"95870a93"]
	... 14 more

Farmer version: v6

Server version: TacoSpigot 1.8

**Comment by poyrazinan** [comment]
@berktuaga neither plugman nor reload command usable for load this plugin. You must restart the server

**Comment by poyrazinan** [comment]
@berktuaga 1.8 GrievPrevention is not suitable for farmer-v6. You can use Farmer-v5 on 1.8 minecraft version.
